version: '3.8'

services:
  # Servicio de Base de Datos MySQL
  library-db:
    image: mysql:8.0
    container_name: library-mysql-cloud
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: library_cloud_db
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - library-cloud-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword123"]
      timeout: 20s
      retries: 10
      interval: 30s

  # Servicio del Backend API
  library-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: library-backend-cloud
    ports:
      - "8001:8000"
    environment:
      - APP_NAME=Library-Cloud-Native
      - APP_ENV=production
      - APP_KEY=base64:llnoCu6JtpRR9+W+0zNUNNqkrMzKkA0vnRu0Gp0Ndlw=
      - APP_DEBUG=false
      - APP_URL=http://localhost:8001
      - DB_CONNECTION=mysql
      - DB_HOST=library-db
      - DB_PORT=3306
      - DB_DATABASE=library_cloud_db
      - DB_USERNAME=library_user
      - DB_PASSWORD=library_password123
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
    depends_on:
      library-db:
        condition: service_healthy
    networks:
      - library-cloud-network
    volumes:
      - ./backend:/var/www
      - backend_storage:/var/www/storage
    restart: unless-stopped
    command: >
      sh -c "
        echo 'Esperando a que la base de datos esté lista...' &&
        sleep 30 &&
        php artisan config:clear &&
        php artisan cache:clear &&
        php artisan migrate:fresh --force &&
        php artisan db:seed --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

volumes:
  mysql_data:
    driver: local
  backend_storage:
    driver: local

networks:
  library-cloud-network:
    driver: bridge
